#!/bin/bash

EXECUTABLE=./JackAnalyzer

SUBMISSION_DIR=$(realpath $(dirname $(find /autograder/submission -name 'setup.sh' -type f)))
echo "Identified ${SUBMISSION_DIR} as root of project."
cp -r ${SUBMISSION_DIR}/* /autograder/source/

pushd /autograder/source/ >/dev/null

# remove any jack or xml files in submission
rm -f *.jack *.xml

# run student-submitted setup script (untrusted)
chmod +x ./setup.sh
timeout -k 15 45 runuser -u student -- ./setup.sh

# in case setup.sh created jack or xml files
rm -f *.jack *.xml

dos2unix ./* 2>/dev/null
chmod ugo+x "${EXECUTABLE}"

popd >/dev/null

# diff outputs with expected
cd /autograder/grader
uv run src/run_tests.py
